### ISSUE TITLE
Create test database for testing

### ISSUE THREAD

**Issue by mkaufmann** [harald-lang/tutor#23]
Test database should have the following characteristics:
- At least two courses, each with groups.
- The courses should have overlapping students.
- Provide list of students that are not in initial student list for the groups and that are than manually added by the tutors. Some of these should have already been in the previous course.

**Comment by kordianbruck** [comment]
@mkaufmann how should this be deployed/used? Do you just need a `.sql` file to create this? 

Its actually pretty easy, to just use the development setup and create those things yourself. What would be much more useful, would be to get some production data, that one could import.

**Comment by MaxEmanuel** [comment]
for the beginning, a simple .sqlite3 file would be enough - how to login from a new created docker?
