### ISSUE TITLE
Separation of code and configuration

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#37]
Default secrets, mailhosts, mail-addresses, etc. should be removed from the repository. - Instead we should provide a quickstart guide that covers all configuration parameters.

**Comment by kordianbruck** [comment]
We have actually removed the whole mail stuff. Secret is an ENV variable named `SECRET_KEY_BASE`.

Apart from that I can only find the sender of the status_mailer to be hard coded. There should not be any additional configuration needed as far as I can tell.

**Comment by kordianbruck** [comment]
Hopefully I've removed all static configuration now. Everything should be in ENV that are documented in the `README.md`
