### ISSUE TITLE
To return to the overview of the group members, button switch user has to be pressed

### ISSUE THREAD

**Issue by maximilianemanuel** [harald-lang/tutor#48]
When having changed to another rider than "Tutor" in the administration view, the button "switch user" has to be pressed to return back to the overview of the group members. Would be nice to return without pushing this button.

**Comment by harald-lang** [comment]
the switch user feature is broken for a long time now. do we really need it?

**Comment by kordianbruck** [comment]
The switch user button is working as expected for me. The only thing seems to be, that the switch does not really "activate" the drop down. The drop down works for me even without activating the "switch".

> the button "switch user" has to be pressed to return back to the overview of the group members.
Which overview of which group members? Do you mean the tutorial view?

Once you select a user from the drop down, the page now reloads. So I guess this is done. Feel free to reopen @maximilianemanuel
