### ISSUE TITLE
automatic switching to current tutorial group throws nil exception

### ISSUE THREAD

**Issue by maximilianemanuel** [harald-lang/tutor#49]
On startup the overview of all group members will switch to current week and to the current tutorial group. But this doesn't work due to an exception that a method is not available on a nil object.

**Comment by lpassing** [comment]
Current work-around: we turned off this feature

**Comment by kordianbruck** [comment]
@lpassing any more info on how you deactivated this? 
@maximilianemanuel this is as a tutor yes? I can't really reproduce this issue - any more hints maybe?

**Comment by MaxEmanuel** [comment]
no, that's from the admin perspective, when you switch to exams, etc. and want to get back to the tutorial view

**Comment by kordianbruck** [comment]
This has been fixed as far as I can tell. Feel free to reopen.
