### ISSUE TITLE
Docker: App state is stored within in the same container.

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#5]

**Comment by mkaufmann** [comment]
State should be stored on reliable storage outside the container. Its unclear how the architecture should be in the future, such that the container can be easily reset if comproside and also reduce the amount of data an attacker might access.

**Comment by harald-lang** [comment]
Changed it to PRIO-URG, because:
1) we cannot update the OS inside container without losing the database
2) we cannot install latest OS security updates, because of 1)

**Comment by harald-lang** [comment]
In general, the application state is not supposed to be stored inside the container.

**Comment by kordianbruck** [comment]
So from what I understand, even production data is kept in a sqlite db in the `/db` folder.
Simplest way to preserve state between two images might be just to mount a host folder to keep those databases: `docker run -v /host/directory:/container/directory`

That way, moving between images will not start a new db each time, but you could keep the previous db fully intact. Rails/Activerecord even provides migrations, so upgrading should not a problem.

**Comment by kordianbruck** [comment]
I don't think we need the `tmp` folder - this can and actually _should_ change between each of the deployments
