### ISSUE TITLE
enable SSL connection

### ISSUE THREAD

**Issue by maximilianemanuel** [harald-lang/tutor#50]
adapt webserver so that SSL connection is enabled and password will be transmitted securely

**Comment by harald-lang** [comment]
One (fast) way to accomplish this is to run Nginx with Letsencrypt as a reverse proxy directly inside the container.

**Comment by kordianbruck** [comment]
SSL should be really part of the hosting webserver, that proxies requests to the docker container. Integrating Lets Encrypt or any other certificate / encryption into the docker image is possible, but not recommended. (We have rate limits for how often we can requests certs, storage of certs, etc. - so not advisable)

For erdb, we already have this set up thanks to @maximilianemanuel at https://erdbtutor.db.in.tum.de

(We could improve this, but right now not a prio: https://www.ssllabs.com/ssltest/analyze.html?d=erdbtutor.db.in.tum.de )
