### ISSUE TITLE
Change license to Apache, BSD, MIT,...

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#52]
copyleft != freedom

**Comment by kordianbruck** [comment]
We'll, if you decide on a license, we can migrate to it. What do you prefer? I'd go with MIT - that's basically do whatever you want. @harald-lang

**Comment by kordianbruck** [comment]
We actually already have a License from Hendrik, so we can't just relicense under MIT. 

Check https://github.com/harald-lang/tutor/blob/master/LICENSE
