### ISSUE TITLE
Install ruby packages as part of Dockerfile instead of startup.sh

### ISSUE THREAD

**Issue by lpassing** [harald-lang/tutor#53]
To improve code-change-to-build time, we should move as much installations as possible from the startup.sh script to the Dockerfile.
Docker allows to only change the scripts folder (=source code) and re-run the startup script, while keeping the image, so this should reduce time it takes to bring code changes to the webserver. Ask André about the details ;-)

**Comment by kordianbruck** [comment]
Done here: https://github.com/harald-lang/tutor/commit/f6b18740e7e386251008671031f9840b929ca4f9
