### ISSUE TITLE
Separate Mailserver and Webserver

### ISSUE THREAD

**Issue by lpassing** [harald-lang/tutor#54]
Docker philosophy is to have just one service per container. There already is an open issue to put the database in a separate container, but we should also separate webserver/mongrel and mailserver/postfix.

**Comment by lpassing** [comment]
#5 Docker: App state is stored within in the same container.

**Comment by kordianbruck** [comment]
I've started to remove anything related to postfix. We really should use a proper SMTP setup for this instead:
https://launchschool.com/blog/handling-emails-in-rails

We should have a smtp account from this, right?

**Comment by kordianbruck** [comment]
@MaxEmanuel do we even need email services? I've checked in the code and can only find one Mail that sends out a token to a student - do we want to keep this? Is it intented for students to login?

Gmail settings: https://www.siteground.com/kb/google_free_smtp_server/

**Comment by MaxEmanuel** [comment]
We need email services for emailing students of a group and for "forgot password" - how is it currently handled?

**Comment by kordianbruck** [comment]
@MaxEmanuel its now possible to use gmail for mailing. I've emailed you the full command, so its easy to get going.
