### ISSUE TITLE
Cannot assign (random) tutors to a course.

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#56]
Associating a tutor with a course, using the "toggle association" function, does not work for random tutors.
After clicking the toggle link, the tutor is still listed as not associated.

**Comment by harald-lang** [comment]
Workaround: Reload page and try again...

**Comment by kordianbruck** [comment]
Next time please check the javascript / browser console for any errors.

I can't reproduce this unfortunately.
