### ISSUE TITLE
Cancel out 4 low order digits of student id.

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#59]

**Comment by kordianbruck** [comment]
@harald-lang isn't this already the case in the tutor view? Or are you talking about some other place?

![screenshot from 2018-03-05 01-00-55](https://user-images.githubusercontent.com/298860/36952465-b255ce96-2010-11e8-80e7-73144ea50001.png)

**Comment by kordianbruck** [comment]
Can be reopened, if its still an issue.
